// Code generated by entc, DO NOT EDIT.

package job

const (
	// Label holds the string label denoting the job type in the database.
	Label = "job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldJobName holds the string denoting the job_name field in the database.
	FieldJobName = "job_name"

	// EdgeJobs holds the string denoting the jobs edge name in mutations.
	EdgeJobs = "jobs"

	// Table holds the table name of the job in the database.
	Table = "jobs"
	// JobsTable is the table the holds the jobs relation/edge.
	JobsTable = "patients"
	// JobsInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	JobsInverseTable = "patients"
	// JobsColumn is the table column denoting the jobs relation/edge.
	JobsColumn = "job_jobs"
)

// Columns holds all SQL columns for job fields.
var Columns = []string{
	FieldID,
	FieldJobName,
}

var (
	// JobNameValidator is a validator for the "Job_name" field. It is called by the builders before save.
	JobNameValidator func(string) error
)
