// Code generated by entc, DO NOT EDIT.

package job

const (
	// Label holds the string label denoting the job type in the database.
	Label = "job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldJobName holds the string denoting the job_name field in the database.
	FieldJobName = "job_name"

	// EdgeJob holds the string denoting the job edge name in mutations.
	EdgeJob = "job"

	// Table holds the table name of the job in the database.
	Table = "jobs"
	// JobTable is the table the holds the job relation/edge.
	JobTable = "jobs"
	// JobInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	JobInverseTable = "patients"
	// JobColumn is the table column denoting the job relation/edge.
	JobColumn = "patient_jobs"
)

// Columns holds all SQL columns for job fields.
var Columns = []string{
	FieldID,
	FieldJobName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Job type.
var ForeignKeys = []string{
	"patient_jobs",
}

var (
	// JobNameValidator is a validator for the "Job_name" field. It is called by the builders before save.
	JobNameValidator func(string) error
)
