// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/panupong/app/ent/gender"
	"github.com/panupong/app/ent/patient"
)

// GenderCreate is the builder for creating a Gender entity.
type GenderCreate struct {
	config
	mutation *GenderMutation
	hooks    []Hook
}

// SetGenderType sets the Gender_type field.
func (gc *GenderCreate) SetGenderType(s string) *GenderCreate {
	gc.mutation.SetGenderType(s)
	return gc
}

// SetGenID sets the gen edge to Patient by id.
func (gc *GenderCreate) SetGenID(id int) *GenderCreate {
	gc.mutation.SetGenID(id)
	return gc
}

// SetNillableGenID sets the gen edge to Patient by id if the given value is not nil.
func (gc *GenderCreate) SetNillableGenID(id *int) *GenderCreate {
	if id != nil {
		gc = gc.SetGenID(*id)
	}
	return gc
}

// SetGen sets the gen edge to Patient.
func (gc *GenderCreate) SetGen(p *Patient) *GenderCreate {
	return gc.SetGenID(p.ID)
}

// Mutation returns the GenderMutation object of the builder.
func (gc *GenderCreate) Mutation() *GenderMutation {
	return gc.mutation
}

// Save creates the Gender in the database.
func (gc *GenderCreate) Save(ctx context.Context) (*Gender, error) {
	if _, ok := gc.mutation.GenderType(); !ok {
		return nil, &ValidationError{Name: "Gender_type", err: errors.New("ent: missing required field \"Gender_type\"")}
	}
	if v, ok := gc.mutation.GenderType(); ok {
		if err := gender.GenderTypeValidator(v); err != nil {
			return nil, &ValidationError{Name: "Gender_type", err: fmt.Errorf("ent: validator failed for field \"Gender_type\": %w", err)}
		}
	}
	var (
		err  error
		node *Gender
	)
	if len(gc.hooks) == 0 {
		node, err = gc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GenderMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			gc.mutation = mutation
			node, err = gc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(gc.hooks) - 1; i >= 0; i-- {
			mut = gc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (gc *GenderCreate) SaveX(ctx context.Context) *Gender {
	v, err := gc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (gc *GenderCreate) sqlSave(ctx context.Context) (*Gender, error) {
	ge, _spec := gc.createSpec()
	if err := sqlgraph.CreateNode(ctx, gc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	ge.ID = int(id)
	return ge, nil
}

func (gc *GenderCreate) createSpec() (*Gender, *sqlgraph.CreateSpec) {
	var (
		ge    = &Gender{config: gc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: gender.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: gender.FieldID,
			},
		}
	)
	if value, ok := gc.mutation.GenderType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: gender.FieldGenderType,
		})
		ge.GenderType = value
	}
	if nodes := gc.mutation.GenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gender.GenTable,
			Columns: []string{gender.GenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return ge, _spec
}
