// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/panupong/app/ent/gender"
	"github.com/panupong/app/ent/patient"
)

// Gender is the model entity for the Gender schema.
type Gender struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// GenderType holds the value of the "Gender_type" field.
	GenderType string `json:"Gender_type,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GenderQuery when eager-loading is set.
	Edges           GenderEdges `json:"edges"`
	patient_genders *int
}

// GenderEdges holds the relations/edges for other nodes in the graph.
type GenderEdges struct {
	// Gen holds the value of the gen edge.
	Gen *Patient
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GenOrErr returns the Gen value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GenderEdges) GenOrErr() (*Patient, error) {
	if e.loadedTypes[0] {
		if e.Gen == nil {
			// The edge gen was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: patient.Label}
		}
		return e.Gen, nil
	}
	return nil, &NotLoadedError{edge: "gen"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Gender) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // Gender_type
	}
}

// fkValues returns the types for scanning foreign-keys values from sql.Rows.
func (*Gender) fkValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // patient_genders
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Gender fields.
func (ge *Gender) assignValues(values ...interface{}) error {
	if m, n := len(values), len(gender.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	ge.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field Gender_type", values[0])
	} else if value.Valid {
		ge.GenderType = value.String
	}
	values = values[1:]
	if len(values) == len(gender.ForeignKeys) {
		if value, ok := values[0].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field patient_genders", value)
		} else if value.Valid {
			ge.patient_genders = new(int)
			*ge.patient_genders = int(value.Int64)
		}
	}
	return nil
}

// QueryGen queries the gen edge of the Gender.
func (ge *Gender) QueryGen() *PatientQuery {
	return (&GenderClient{config: ge.config}).QueryGen(ge)
}

// Update returns a builder for updating this Gender.
// Note that, you need to call Gender.Unwrap() before calling this method, if this Gender
// was returned from a transaction, and the transaction was committed or rolled back.
func (ge *Gender) Update() *GenderUpdateOne {
	return (&GenderClient{config: ge.config}).UpdateOne(ge)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (ge *Gender) Unwrap() *Gender {
	tx, ok := ge.config.driver.(*txDriver)
	if !ok {
		panic("ent: Gender is not a transactional entity")
	}
	ge.config.driver = tx.drv
	return ge
}

// String implements the fmt.Stringer.
func (ge *Gender) String() string {
	var builder strings.Builder
	builder.WriteString("Gender(")
	builder.WriteString(fmt.Sprintf("id=%v", ge.ID))
	builder.WriteString(", Gender_type=")
	builder.WriteString(ge.GenderType)
	builder.WriteByte(')')
	return builder.String()
}

// Genders is a parsable slice of Gender.
type Genders []*Gender

func (ge Genders) config(cfg config) {
	for _i := range ge {
		ge[_i].config = cfg
	}
}
