// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/panupong/app/ent/gender"
	"github.com/panupong/app/ent/job"
	"github.com/panupong/app/ent/patient"
	"github.com/panupong/app/ent/predicate"
	"github.com/panupong/app/ent/title"
)

// PatientUpdate is the builder for updating Patient entities.
type PatientUpdate struct {
	config
	hooks      []Hook
	mutation   *PatientMutation
	predicates []predicate.Patient
}

// Where adds a new predicate for the builder.
func (pu *PatientUpdate) Where(ps ...predicate.Patient) *PatientUpdate {
	pu.predicates = append(pu.predicates, ps...)
	return pu
}

// SetCardID sets the Card_id field.
func (pu *PatientUpdate) SetCardID(s string) *PatientUpdate {
	pu.mutation.SetCardID(s)
	return pu
}

// SetFistName sets the Fist_name field.
func (pu *PatientUpdate) SetFistName(s string) *PatientUpdate {
	pu.mutation.SetFistName(s)
	return pu
}

// SetLastName sets the Last_name field.
func (pu *PatientUpdate) SetLastName(s string) *PatientUpdate {
	pu.mutation.SetLastName(s)
	return pu
}

// SetAllergic sets the Allergic field.
func (pu *PatientUpdate) SetAllergic(s string) *PatientUpdate {
	pu.mutation.SetAllergic(s)
	return pu
}

// SetAge sets the age field.
func (pu *PatientUpdate) SetAge(i int) *PatientUpdate {
	pu.mutation.ResetAge()
	pu.mutation.SetAge(i)
	return pu
}

// AddAge adds i to age.
func (pu *PatientUpdate) AddAge(i int) *PatientUpdate {
	pu.mutation.AddAge(i)
	return pu
}

// SetPatientsID sets the patients edge to Gender by id.
func (pu *PatientUpdate) SetPatientsID(id int) *PatientUpdate {
	pu.mutation.SetPatientsID(id)
	return pu
}

// SetNillablePatientsID sets the patients edge to Gender by id if the given value is not nil.
func (pu *PatientUpdate) SetNillablePatientsID(id *int) *PatientUpdate {
	if id != nil {
		pu = pu.SetPatientsID(*id)
	}
	return pu
}

// SetPatients sets the patients edge to Gender.
func (pu *PatientUpdate) SetPatients(g *Gender) *PatientUpdate {
	return pu.SetPatientsID(g.ID)
}

// SetPatients1ID sets the patients1 edge to Title by id.
func (pu *PatientUpdate) SetPatients1ID(id int) *PatientUpdate {
	pu.mutation.SetPatients1ID(id)
	return pu
}

// SetNillablePatients1ID sets the patients1 edge to Title by id if the given value is not nil.
func (pu *PatientUpdate) SetNillablePatients1ID(id *int) *PatientUpdate {
	if id != nil {
		pu = pu.SetPatients1ID(*id)
	}
	return pu
}

// SetPatients1 sets the patients1 edge to Title.
func (pu *PatientUpdate) SetPatients1(t *Title) *PatientUpdate {
	return pu.SetPatients1ID(t.ID)
}

// SetPatients2ID sets the patients2 edge to Job by id.
func (pu *PatientUpdate) SetPatients2ID(id int) *PatientUpdate {
	pu.mutation.SetPatients2ID(id)
	return pu
}

// SetNillablePatients2ID sets the patients2 edge to Job by id if the given value is not nil.
func (pu *PatientUpdate) SetNillablePatients2ID(id *int) *PatientUpdate {
	if id != nil {
		pu = pu.SetPatients2ID(*id)
	}
	return pu
}

// SetPatients2 sets the patients2 edge to Job.
func (pu *PatientUpdate) SetPatients2(j *Job) *PatientUpdate {
	return pu.SetPatients2ID(j.ID)
}

// Mutation returns the PatientMutation object of the builder.
func (pu *PatientUpdate) Mutation() *PatientMutation {
	return pu.mutation
}

// ClearPatients clears the patients edge to Gender.
func (pu *PatientUpdate) ClearPatients() *PatientUpdate {
	pu.mutation.ClearPatients()
	return pu
}

// ClearPatients1 clears the patients1 edge to Title.
func (pu *PatientUpdate) ClearPatients1() *PatientUpdate {
	pu.mutation.ClearPatients1()
	return pu
}

// ClearPatients2 clears the patients2 edge to Job.
func (pu *PatientUpdate) ClearPatients2() *PatientUpdate {
	pu.mutation.ClearPatients2()
	return pu
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (pu *PatientUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := pu.mutation.CardID(); ok {
		if err := patient.CardIDValidator(v); err != nil {
			return 0, &ValidationError{Name: "Card_id", err: fmt.Errorf("ent: validator failed for field \"Card_id\": %w", err)}
		}
	}
	if v, ok := pu.mutation.FistName(); ok {
		if err := patient.FistNameValidator(v); err != nil {
			return 0, &ValidationError{Name: "Fist_name", err: fmt.Errorf("ent: validator failed for field \"Fist_name\": %w", err)}
		}
	}
	if v, ok := pu.mutation.LastName(); ok {
		if err := patient.LastNameValidator(v); err != nil {
			return 0, &ValidationError{Name: "Last_name", err: fmt.Errorf("ent: validator failed for field \"Last_name\": %w", err)}
		}
	}
	if v, ok := pu.mutation.Allergic(); ok {
		if err := patient.AllergicValidator(v); err != nil {
			return 0, &ValidationError{Name: "Allergic", err: fmt.Errorf("ent: validator failed for field \"Allergic\": %w", err)}
		}
	}
	if v, ok := pu.mutation.Age(); ok {
		if err := patient.AgeValidator(v); err != nil {
			return 0, &ValidationError{Name: "age", err: fmt.Errorf("ent: validator failed for field \"age\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(pu.hooks) == 0 {
		affected, err = pu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PatientMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pu.mutation = mutation
			affected, err = pu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pu.hooks) - 1; i >= 0; i-- {
			mut = pu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PatientUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PatientUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PatientUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *PatientUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   patient.Table,
			Columns: patient.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: patient.FieldID,
			},
		},
	}
	if ps := pu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.CardID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldCardID,
		})
	}
	if value, ok := pu.mutation.FistName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldFistName,
		})
	}
	if value, ok := pu.mutation.LastName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldLastName,
		})
	}
	if value, ok := pu.mutation.Allergic(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldAllergic,
		})
	}
	if value, ok := pu.mutation.Age(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: patient.FieldAge,
		})
	}
	if value, ok := pu.mutation.AddedAge(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: patient.FieldAge,
		})
	}
	if pu.mutation.PatientsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patient.PatientsTable,
			Columns: []string{patient.PatientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: gender.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.PatientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patient.PatientsTable,
			Columns: []string{patient.PatientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: gender.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.Patients1Cleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patient.Patients1Table,
			Columns: []string{patient.Patients1Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: title.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.Patients1IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patient.Patients1Table,
			Columns: []string{patient.Patients1Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: title.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.Patients2Cleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patient.Patients2Table,
			Columns: []string{patient.Patients2Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: job.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.Patients2IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patient.Patients2Table,
			Columns: []string{patient.Patients2Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: job.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{patient.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// PatientUpdateOne is the builder for updating a single Patient entity.
type PatientUpdateOne struct {
	config
	hooks    []Hook
	mutation *PatientMutation
}

// SetCardID sets the Card_id field.
func (puo *PatientUpdateOne) SetCardID(s string) *PatientUpdateOne {
	puo.mutation.SetCardID(s)
	return puo
}

// SetFistName sets the Fist_name field.
func (puo *PatientUpdateOne) SetFistName(s string) *PatientUpdateOne {
	puo.mutation.SetFistName(s)
	return puo
}

// SetLastName sets the Last_name field.
func (puo *PatientUpdateOne) SetLastName(s string) *PatientUpdateOne {
	puo.mutation.SetLastName(s)
	return puo
}

// SetAllergic sets the Allergic field.
func (puo *PatientUpdateOne) SetAllergic(s string) *PatientUpdateOne {
	puo.mutation.SetAllergic(s)
	return puo
}

// SetAge sets the age field.
func (puo *PatientUpdateOne) SetAge(i int) *PatientUpdateOne {
	puo.mutation.ResetAge()
	puo.mutation.SetAge(i)
	return puo
}

// AddAge adds i to age.
func (puo *PatientUpdateOne) AddAge(i int) *PatientUpdateOne {
	puo.mutation.AddAge(i)
	return puo
}

// SetPatientsID sets the patients edge to Gender by id.
func (puo *PatientUpdateOne) SetPatientsID(id int) *PatientUpdateOne {
	puo.mutation.SetPatientsID(id)
	return puo
}

// SetNillablePatientsID sets the patients edge to Gender by id if the given value is not nil.
func (puo *PatientUpdateOne) SetNillablePatientsID(id *int) *PatientUpdateOne {
	if id != nil {
		puo = puo.SetPatientsID(*id)
	}
	return puo
}

// SetPatients sets the patients edge to Gender.
func (puo *PatientUpdateOne) SetPatients(g *Gender) *PatientUpdateOne {
	return puo.SetPatientsID(g.ID)
}

// SetPatients1ID sets the patients1 edge to Title by id.
func (puo *PatientUpdateOne) SetPatients1ID(id int) *PatientUpdateOne {
	puo.mutation.SetPatients1ID(id)
	return puo
}

// SetNillablePatients1ID sets the patients1 edge to Title by id if the given value is not nil.
func (puo *PatientUpdateOne) SetNillablePatients1ID(id *int) *PatientUpdateOne {
	if id != nil {
		puo = puo.SetPatients1ID(*id)
	}
	return puo
}

// SetPatients1 sets the patients1 edge to Title.
func (puo *PatientUpdateOne) SetPatients1(t *Title) *PatientUpdateOne {
	return puo.SetPatients1ID(t.ID)
}

// SetPatients2ID sets the patients2 edge to Job by id.
func (puo *PatientUpdateOne) SetPatients2ID(id int) *PatientUpdateOne {
	puo.mutation.SetPatients2ID(id)
	return puo
}

// SetNillablePatients2ID sets the patients2 edge to Job by id if the given value is not nil.
func (puo *PatientUpdateOne) SetNillablePatients2ID(id *int) *PatientUpdateOne {
	if id != nil {
		puo = puo.SetPatients2ID(*id)
	}
	return puo
}

// SetPatients2 sets the patients2 edge to Job.
func (puo *PatientUpdateOne) SetPatients2(j *Job) *PatientUpdateOne {
	return puo.SetPatients2ID(j.ID)
}

// Mutation returns the PatientMutation object of the builder.
func (puo *PatientUpdateOne) Mutation() *PatientMutation {
	return puo.mutation
}

// ClearPatients clears the patients edge to Gender.
func (puo *PatientUpdateOne) ClearPatients() *PatientUpdateOne {
	puo.mutation.ClearPatients()
	return puo
}

// ClearPatients1 clears the patients1 edge to Title.
func (puo *PatientUpdateOne) ClearPatients1() *PatientUpdateOne {
	puo.mutation.ClearPatients1()
	return puo
}

// ClearPatients2 clears the patients2 edge to Job.
func (puo *PatientUpdateOne) ClearPatients2() *PatientUpdateOne {
	puo.mutation.ClearPatients2()
	return puo
}

// Save executes the query and returns the updated entity.
func (puo *PatientUpdateOne) Save(ctx context.Context) (*Patient, error) {
	if v, ok := puo.mutation.CardID(); ok {
		if err := patient.CardIDValidator(v); err != nil {
			return nil, &ValidationError{Name: "Card_id", err: fmt.Errorf("ent: validator failed for field \"Card_id\": %w", err)}
		}
	}
	if v, ok := puo.mutation.FistName(); ok {
		if err := patient.FistNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "Fist_name", err: fmt.Errorf("ent: validator failed for field \"Fist_name\": %w", err)}
		}
	}
	if v, ok := puo.mutation.LastName(); ok {
		if err := patient.LastNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "Last_name", err: fmt.Errorf("ent: validator failed for field \"Last_name\": %w", err)}
		}
	}
	if v, ok := puo.mutation.Allergic(); ok {
		if err := patient.AllergicValidator(v); err != nil {
			return nil, &ValidationError{Name: "Allergic", err: fmt.Errorf("ent: validator failed for field \"Allergic\": %w", err)}
		}
	}
	if v, ok := puo.mutation.Age(); ok {
		if err := patient.AgeValidator(v); err != nil {
			return nil, &ValidationError{Name: "age", err: fmt.Errorf("ent: validator failed for field \"age\": %w", err)}
		}
	}

	var (
		err  error
		node *Patient
	)
	if len(puo.hooks) == 0 {
		node, err = puo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PatientMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			puo.mutation = mutation
			node, err = puo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(puo.hooks) - 1; i >= 0; i-- {
			mut = puo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, puo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PatientUpdateOne) SaveX(ctx context.Context) *Patient {
	pa, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return pa
}

// Exec executes the query on the entity.
func (puo *PatientUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PatientUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *PatientUpdateOne) sqlSave(ctx context.Context) (pa *Patient, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   patient.Table,
			Columns: patient.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: patient.FieldID,
			},
		},
	}
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Patient.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := puo.mutation.CardID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldCardID,
		})
	}
	if value, ok := puo.mutation.FistName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldFistName,
		})
	}
	if value, ok := puo.mutation.LastName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldLastName,
		})
	}
	if value, ok := puo.mutation.Allergic(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldAllergic,
		})
	}
	if value, ok := puo.mutation.Age(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: patient.FieldAge,
		})
	}
	if value, ok := puo.mutation.AddedAge(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: patient.FieldAge,
		})
	}
	if puo.mutation.PatientsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patient.PatientsTable,
			Columns: []string{patient.PatientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: gender.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.PatientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patient.PatientsTable,
			Columns: []string{patient.PatientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: gender.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.Patients1Cleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patient.Patients1Table,
			Columns: []string{patient.Patients1Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: title.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.Patients1IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patient.Patients1Table,
			Columns: []string{patient.Patients1Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: title.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.Patients2Cleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patient.Patients2Table,
			Columns: []string{patient.Patients2Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: job.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.Patients2IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patient.Patients2Table,
			Columns: []string{patient.Patients2Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: job.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	pa = &Patient{config: puo.config}
	_spec.Assign = pa.assignValues
	_spec.ScanValues = pa.scanValues()
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{patient.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return pa, nil
}
