// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/panupong/app/ent/patient"
)

// Patient is the model entity for the Patient schema.
type Patient struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CardID holds the value of the "Card_id" field.
	CardID string `json:"Card_id,omitempty"`
	// FistName holds the value of the "Fist_name" field.
	FistName string `json:"Fist_name,omitempty"`
	// LastName holds the value of the "Last_name" field.
	LastName string `json:"Last_name,omitempty"`
	// Allergic holds the value of the "Allergic" field.
	Allergic string `json:"Allergic,omitempty"`
	// Age holds the value of the "age" field.
	Age int `json:"age,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PatientQuery when eager-loading is set.
	Edges PatientEdges `json:"edges"`
}

// PatientEdges holds the relations/edges for other nodes in the graph.
type PatientEdges struct {
	// Genders holds the value of the genders edge.
	Genders []*Gender
	// Titles holds the value of the titles edge.
	Titles []*Title
	// Jobs holds the value of the jobs edge.
	Jobs []*Job
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// GendersOrErr returns the Genders value or an error if the edge
// was not loaded in eager-loading.
func (e PatientEdges) GendersOrErr() ([]*Gender, error) {
	if e.loadedTypes[0] {
		return e.Genders, nil
	}
	return nil, &NotLoadedError{edge: "genders"}
}

// TitlesOrErr returns the Titles value or an error if the edge
// was not loaded in eager-loading.
func (e PatientEdges) TitlesOrErr() ([]*Title, error) {
	if e.loadedTypes[1] {
		return e.Titles, nil
	}
	return nil, &NotLoadedError{edge: "titles"}
}

// JobsOrErr returns the Jobs value or an error if the edge
// was not loaded in eager-loading.
func (e PatientEdges) JobsOrErr() ([]*Job, error) {
	if e.loadedTypes[2] {
		return e.Jobs, nil
	}
	return nil, &NotLoadedError{edge: "jobs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Patient) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // Card_id
		&sql.NullString{}, // Fist_name
		&sql.NullString{}, // Last_name
		&sql.NullString{}, // Allergic
		&sql.NullInt64{},  // age
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Patient fields.
func (pa *Patient) assignValues(values ...interface{}) error {
	if m, n := len(values), len(patient.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	pa.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field Card_id", values[0])
	} else if value.Valid {
		pa.CardID = value.String
	}
	if value, ok := values[1].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field Fist_name", values[1])
	} else if value.Valid {
		pa.FistName = value.String
	}
	if value, ok := values[2].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field Last_name", values[2])
	} else if value.Valid {
		pa.LastName = value.String
	}
	if value, ok := values[3].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field Allergic", values[3])
	} else if value.Valid {
		pa.Allergic = value.String
	}
	if value, ok := values[4].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field age", values[4])
	} else if value.Valid {
		pa.Age = int(value.Int64)
	}
	return nil
}

// QueryGenders queries the genders edge of the Patient.
func (pa *Patient) QueryGenders() *GenderQuery {
	return (&PatientClient{config: pa.config}).QueryGenders(pa)
}

// QueryTitles queries the titles edge of the Patient.
func (pa *Patient) QueryTitles() *TitleQuery {
	return (&PatientClient{config: pa.config}).QueryTitles(pa)
}

// QueryJobs queries the jobs edge of the Patient.
func (pa *Patient) QueryJobs() *JobQuery {
	return (&PatientClient{config: pa.config}).QueryJobs(pa)
}

// Update returns a builder for updating this Patient.
// Note that, you need to call Patient.Unwrap() before calling this method, if this Patient
// was returned from a transaction, and the transaction was committed or rolled back.
func (pa *Patient) Update() *PatientUpdateOne {
	return (&PatientClient{config: pa.config}).UpdateOne(pa)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (pa *Patient) Unwrap() *Patient {
	tx, ok := pa.config.driver.(*txDriver)
	if !ok {
		panic("ent: Patient is not a transactional entity")
	}
	pa.config.driver = tx.drv
	return pa
}

// String implements the fmt.Stringer.
func (pa *Patient) String() string {
	var builder strings.Builder
	builder.WriteString("Patient(")
	builder.WriteString(fmt.Sprintf("id=%v", pa.ID))
	builder.WriteString(", Card_id=")
	builder.WriteString(pa.CardID)
	builder.WriteString(", Fist_name=")
	builder.WriteString(pa.FistName)
	builder.WriteString(", Last_name=")
	builder.WriteString(pa.LastName)
	builder.WriteString(", Allergic=")
	builder.WriteString(pa.Allergic)
	builder.WriteString(", age=")
	builder.WriteString(fmt.Sprintf("%v", pa.Age))
	builder.WriteByte(')')
	return builder.String()
}

// Patients is a parsable slice of Patient.
type Patients []*Patient

func (pa Patients) config(cfg config) {
	for _i := range pa {
		pa[_i].config = cfg
	}
}
