// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/panupong/app/ent/gender"
	"github.com/panupong/app/ent/job"
	"github.com/panupong/app/ent/patient"
	"github.com/panupong/app/ent/title"
)

// Patient is the model entity for the Patient schema.
type Patient struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CardID holds the value of the "Card_id" field.
	CardID string `json:"Card_id,omitempty"`
	// FistName holds the value of the "Fist_name" field.
	FistName string `json:"Fist_name,omitempty"`
	// LastName holds the value of the "Last_name" field.
	LastName string `json:"Last_name,omitempty"`
	// Allergic holds the value of the "Allergic" field.
	Allergic string `json:"Allergic,omitempty"`
	// Age holds the value of the "age" field.
	Age int `json:"age,omitempty"`
	// Birthday holds the value of the "Birthday" field.
	Birthday time.Time `json:"Birthday,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PatientQuery when eager-loading is set.
	Edges          PatientEdges `json:"edges"`
	gender_genders *int
	job_jobs       *int
	title_titles   *int
}

// PatientEdges holds the relations/edges for other nodes in the graph.
type PatientEdges struct {
	// Patients holds the value of the patients edge.
	Patients *Gender
	// Patients1 holds the value of the patients1 edge.
	Patients1 *Title
	// Patients2 holds the value of the patients2 edge.
	Patients2 *Job
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// PatientsOrErr returns the Patients value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PatientEdges) PatientsOrErr() (*Gender, error) {
	if e.loadedTypes[0] {
		if e.Patients == nil {
			// The edge patients was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: gender.Label}
		}
		return e.Patients, nil
	}
	return nil, &NotLoadedError{edge: "patients"}
}

// Patients1OrErr returns the Patients1 value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PatientEdges) Patients1OrErr() (*Title, error) {
	if e.loadedTypes[1] {
		if e.Patients1 == nil {
			// The edge patients1 was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: title.Label}
		}
		return e.Patients1, nil
	}
	return nil, &NotLoadedError{edge: "patients1"}
}

// Patients2OrErr returns the Patients2 value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PatientEdges) Patients2OrErr() (*Job, error) {
	if e.loadedTypes[2] {
		if e.Patients2 == nil {
			// The edge patients2 was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: job.Label}
		}
		return e.Patients2, nil
	}
	return nil, &NotLoadedError{edge: "patients2"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Patient) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // Card_id
		&sql.NullString{}, // Fist_name
		&sql.NullString{}, // Last_name
		&sql.NullString{}, // Allergic
		&sql.NullInt64{},  // age
		&sql.NullTime{},   // Birthday
	}
}

// fkValues returns the types for scanning foreign-keys values from sql.Rows.
func (*Patient) fkValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // gender_genders
		&sql.NullInt64{}, // job_jobs
		&sql.NullInt64{}, // title_titles
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Patient fields.
func (pa *Patient) assignValues(values ...interface{}) error {
	if m, n := len(values), len(patient.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	pa.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field Card_id", values[0])
	} else if value.Valid {
		pa.CardID = value.String
	}
	if value, ok := values[1].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field Fist_name", values[1])
	} else if value.Valid {
		pa.FistName = value.String
	}
	if value, ok := values[2].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field Last_name", values[2])
	} else if value.Valid {
		pa.LastName = value.String
	}
	if value, ok := values[3].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field Allergic", values[3])
	} else if value.Valid {
		pa.Allergic = value.String
	}
	if value, ok := values[4].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field age", values[4])
	} else if value.Valid {
		pa.Age = int(value.Int64)
	}
	if value, ok := values[5].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field Birthday", values[5])
	} else if value.Valid {
		pa.Birthday = value.Time
	}
	values = values[6:]
	if len(values) == len(patient.ForeignKeys) {
		if value, ok := values[0].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field gender_genders", value)
		} else if value.Valid {
			pa.gender_genders = new(int)
			*pa.gender_genders = int(value.Int64)
		}
		if value, ok := values[1].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field job_jobs", value)
		} else if value.Valid {
			pa.job_jobs = new(int)
			*pa.job_jobs = int(value.Int64)
		}
		if value, ok := values[2].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field title_titles", value)
		} else if value.Valid {
			pa.title_titles = new(int)
			*pa.title_titles = int(value.Int64)
		}
	}
	return nil
}

// QueryPatients queries the patients edge of the Patient.
func (pa *Patient) QueryPatients() *GenderQuery {
	return (&PatientClient{config: pa.config}).QueryPatients(pa)
}

// QueryPatients1 queries the patients1 edge of the Patient.
func (pa *Patient) QueryPatients1() *TitleQuery {
	return (&PatientClient{config: pa.config}).QueryPatients1(pa)
}

// QueryPatients2 queries the patients2 edge of the Patient.
func (pa *Patient) QueryPatients2() *JobQuery {
	return (&PatientClient{config: pa.config}).QueryPatients2(pa)
}

// Update returns a builder for updating this Patient.
// Note that, you need to call Patient.Unwrap() before calling this method, if this Patient
// was returned from a transaction, and the transaction was committed or rolled back.
func (pa *Patient) Update() *PatientUpdateOne {
	return (&PatientClient{config: pa.config}).UpdateOne(pa)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (pa *Patient) Unwrap() *Patient {
	tx, ok := pa.config.driver.(*txDriver)
	if !ok {
		panic("ent: Patient is not a transactional entity")
	}
	pa.config.driver = tx.drv
	return pa
}

// String implements the fmt.Stringer.
func (pa *Patient) String() string {
	var builder strings.Builder
	builder.WriteString("Patient(")
	builder.WriteString(fmt.Sprintf("id=%v", pa.ID))
	builder.WriteString(", Card_id=")
	builder.WriteString(pa.CardID)
	builder.WriteString(", Fist_name=")
	builder.WriteString(pa.FistName)
	builder.WriteString(", Last_name=")
	builder.WriteString(pa.LastName)
	builder.WriteString(", Allergic=")
	builder.WriteString(pa.Allergic)
	builder.WriteString(", age=")
	builder.WriteString(fmt.Sprintf("%v", pa.Age))
	builder.WriteString(", Birthday=")
	builder.WriteString(pa.Birthday.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Patients is a parsable slice of Patient.
type Patients []*Patient

func (pa Patients) config(cfg config) {
	for _i := range pa {
		pa[_i].config = cfg
	}
}
