// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// GendersColumns holds the columns for the "genders" table.
	GendersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "gender_type", Type: field.TypeString},
		{Name: "patient_genders", Type: field.TypeInt, Nullable: true},
	}
	// GendersTable holds the schema information for the "genders" table.
	GendersTable = &schema.Table{
		Name:       "genders",
		Columns:    GendersColumns,
		PrimaryKey: []*schema.Column{GendersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "genders_patients_genders",
				Columns: []*schema.Column{GendersColumns[2]},

				RefColumns: []*schema.Column{PatientsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// JobsColumns holds the columns for the "jobs" table.
	JobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "job_name", Type: field.TypeString},
		{Name: "patient_jobs", Type: field.TypeInt, Nullable: true},
	}
	// JobsTable holds the schema information for the "jobs" table.
	JobsTable = &schema.Table{
		Name:       "jobs",
		Columns:    JobsColumns,
		PrimaryKey: []*schema.Column{JobsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "jobs_patients_jobs",
				Columns: []*schema.Column{JobsColumns[2]},

				RefColumns: []*schema.Column{PatientsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// PatientsColumns holds the columns for the "patients" table.
	PatientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "card_id", Type: field.TypeString},
		{Name: "fist_name", Type: field.TypeString},
		{Name: "last_name", Type: field.TypeString},
		{Name: "allergic", Type: field.TypeString},
		{Name: "age", Type: field.TypeInt},
	}
	// PatientsTable holds the schema information for the "patients" table.
	PatientsTable = &schema.Table{
		Name:        "patients",
		Columns:     PatientsColumns,
		PrimaryKey:  []*schema.Column{PatientsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// TitlesColumns holds the columns for the "titles" table.
	TitlesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title_type", Type: field.TypeString},
		{Name: "patient_titles", Type: field.TypeInt, Nullable: true},
	}
	// TitlesTable holds the schema information for the "titles" table.
	TitlesTable = &schema.Table{
		Name:       "titles",
		Columns:    TitlesColumns,
		PrimaryKey: []*schema.Column{TitlesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "titles_patients_titles",
				Columns: []*schema.Column{TitlesColumns[2]},

				RefColumns: []*schema.Column{PatientsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GendersTable,
		JobsTable,
		PatientsTable,
		TitlesTable,
	}
)

func init() {
	GendersTable.ForeignKeys[0].RefTable = PatientsTable
	JobsTable.ForeignKeys[0].RefTable = PatientsTable
	TitlesTable.ForeignKeys[0].RefTable = PatientsTable
}
