// Code generated by entc, DO NOT EDIT.

package title

const (
	// Label holds the string label denoting the title type in the database.
	Label = "title"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitleType holds the string denoting the title_type field in the database.
	FieldTitleType = "title_type"

	// EdgeTitle holds the string denoting the title edge name in mutations.
	EdgeTitle = "title"

	// Table holds the table name of the title in the database.
	Table = "titles"
	// TitleTable is the table the holds the title relation/edge.
	TitleTable = "titles"
	// TitleInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	TitleInverseTable = "patients"
	// TitleColumn is the table column denoting the title relation/edge.
	TitleColumn = "patient_titles"
)

// Columns holds all SQL columns for title fields.
var Columns = []string{
	FieldID,
	FieldTitleType,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Title type.
var ForeignKeys = []string{
	"patient_titles",
}

var (
	// TitleTypeValidator is a validator for the "Title_type" field. It is called by the builders before save.
	TitleTypeValidator func(string) error
)
