// Code generated by entc, DO NOT EDIT.

package gender

const (
	// Label holds the string label denoting the gender type in the database.
	Label = "gender"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGenderType holds the string denoting the gender_type field in the database.
	FieldGenderType = "gender_type"

	// EdgeGen holds the string denoting the gen edge name in mutations.
	EdgeGen = "gen"

	// Table holds the table name of the gender in the database.
	Table = "genders"
	// GenTable is the table the holds the gen relation/edge.
	GenTable = "genders"
	// GenInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	GenInverseTable = "patients"
	// GenColumn is the table column denoting the gen relation/edge.
	GenColumn = "patient_genders"
)

// Columns holds all SQL columns for gender fields.
var Columns = []string{
	FieldID,
	FieldGenderType,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Gender type.
var ForeignKeys = []string{
	"patient_genders",
}

var (
	// GenderTypeValidator is a validator for the "Gender_type" field. It is called by the builders before save.
	GenderTypeValidator func(string) error
)
